/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackage;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import java.util.concurrent.TimeUnit;
/**
 *
 * @author AK
 */
public class AddTaskFrame extends javax.swing.JFrame {
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
    database db = new database();
    /**
     * Creates new form AddTaskFrame
     */
    homeFrame MainFrame;
    public AddTaskFrame(homeFrame MainFrame) {
        initComponents();
        this.MainFrame = MainFrame;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        AddTaskPanel = new javax.swing.JPanel();
        addTaskNamePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtAddTaskName = new javax.swing.JTextField();
        addTaskUnitPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtAddTaskUnit = new javax.swing.JTextField();
        addTaskWorkTargetPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtAddTaskWorkTarget = new javax.swing.JTextField();
        addTaskWorkCompletePanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtAddTaskWorkComplete = new javax.swing.JTextField();
        addTaskStartPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        startDateChooser = new com.toedter.calendar.JDateChooser();
        txtAddTaskStartTime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addTaskEndPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        endDateChooser = new com.toedter.calendar.JDateChooser();
        txtAddTaskEndTime = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnAddTaskSubmit = new javax.swing.JButton();
        btnAddTaskCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel11.setText("Name                  :");

        txtAddTaskName.setText(" ");

        javax.swing.GroupLayout addTaskNamePanelLayout = new javax.swing.GroupLayout(addTaskNamePanel);
        addTaskNamePanel.setLayout(addTaskNamePanelLayout);
        addTaskNamePanelLayout.setHorizontalGroup(
            addTaskNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddTaskName)
                .addContainerGap())
        );
        addTaskNamePanelLayout.setVerticalGroup(
            addTaskNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTaskNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(txtAddTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel12.setText("Unit                     :");

        txtAddTaskUnit.setText(" ");

        javax.swing.GroupLayout addTaskUnitPanelLayout = new javax.swing.GroupLayout(addTaskUnitPanel);
        addTaskUnitPanel.setLayout(addTaskUnitPanelLayout);
        addTaskUnitPanelLayout.setHorizontalGroup(
            addTaskUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskUnitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddTaskUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        addTaskUnitPanelLayout.setVerticalGroup(
            addTaskUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskUnitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTaskUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(txtAddTaskUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel13.setText("Work Target       :");

        txtAddTaskWorkTarget.setText(" ");

        javax.swing.GroupLayout addTaskWorkTargetPanelLayout = new javax.swing.GroupLayout(addTaskWorkTargetPanel);
        addTaskWorkTargetPanel.setLayout(addTaskWorkTargetPanelLayout);
        addTaskWorkTargetPanelLayout.setHorizontalGroup(
            addTaskWorkTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskWorkTargetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddTaskWorkTarget, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        addTaskWorkTargetPanelLayout.setVerticalGroup(
            addTaskWorkTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskWorkTargetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTaskWorkTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(txtAddTaskWorkTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel14.setText("Work Complete :");

        txtAddTaskWorkComplete.setText(" ");

        javax.swing.GroupLayout addTaskWorkCompletePanelLayout = new javax.swing.GroupLayout(addTaskWorkCompletePanel);
        addTaskWorkCompletePanel.setLayout(addTaskWorkCompletePanelLayout);
        addTaskWorkCompletePanelLayout.setHorizontalGroup(
            addTaskWorkCompletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskWorkCompletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddTaskWorkComplete, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        addTaskWorkCompletePanelLayout.setVerticalGroup(
            addTaskWorkCompletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskWorkCompletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTaskWorkCompletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(txtAddTaskWorkComplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Start");
        jLabel1.setToolTipText("");

        jLabel2.setText("Day");

        jLabel3.setText("Time");

        txtAddTaskStartTime.setText("00:00");

        jLabel7.setText("(HH:MM) - 24 hr");

        javax.swing.GroupLayout addTaskStartPanelLayout = new javax.swing.GroupLayout(addTaskStartPanel);
        addTaskStartPanel.setLayout(addTaskStartPanelLayout);
        addTaskStartPanelLayout.setHorizontalGroup(
            addTaskStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskStartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addTaskStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addTaskStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addTaskStartPanelLayout.createSequentialGroup()
                        .addComponent(txtAddTaskStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addTaskStartPanelLayout.setVerticalGroup(
            addTaskStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskStartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTaskStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addTaskStartPanelLayout.createSequentialGroup()
                        .addGroup(addTaskStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addTaskStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddTaskStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("End");
        jLabel8.setToolTipText("");

        jLabel9.setText("Day");

        jLabel10.setText("Time");

        txtAddTaskEndTime.setText("00:00");
        txtAddTaskEndTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddTaskEndTimeActionPerformed(evt);
            }
        });

        jLabel15.setText("(HH:MM) - 24 hr");

        javax.swing.GroupLayout addTaskEndPanelLayout = new javax.swing.GroupLayout(addTaskEndPanel);
        addTaskEndPanel.setLayout(addTaskEndPanelLayout);
        addTaskEndPanelLayout.setHorizontalGroup(
            addTaskEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskEndPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addTaskEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addTaskEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addTaskEndPanelLayout.createSequentialGroup()
                        .addComponent(txtAddTaskEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addTaskEndPanelLayout.setVerticalGroup(
            addTaskEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskEndPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTaskEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addTaskEndPanelLayout.createSequentialGroup()
                        .addGroup(addTaskEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addTaskEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddTaskEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnAddTaskSubmit.setText("Submit");
        btnAddTaskSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskSubmitActionPerformed(evt);
            }
        });

        btnAddTaskCancel.setText("Cancel");
        btnAddTaskCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddTaskPanelLayout = new javax.swing.GroupLayout(AddTaskPanel);
        AddTaskPanel.setLayout(AddTaskPanelLayout);
        AddTaskPanelLayout.setHorizontalGroup(
            AddTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTaskNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addTaskUnitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addTaskWorkTargetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addTaskWorkCompletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addTaskStartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addTaskEndPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddTaskPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddTaskSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnAddTaskCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        AddTaskPanelLayout.setVerticalGroup(
            AddTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTaskPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(addTaskNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTaskUnitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTaskWorkTargetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTaskWorkCompletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTaskStartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTaskEndPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AddTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTaskSubmit)
                    .addComponent(btnAddTaskCancel))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddTaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AddTaskPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddTaskEndTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddTaskEndTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddTaskEndTimeActionPerformed

    private void btnAddTaskSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskSubmitActionPerformed
        // TODO add your handling code here:
        String Name = txtAddTaskName.getText();
        String Unit = txtAddTaskUnit.getText();
        String WorkTarget = txtAddTaskWorkTarget.getText();
        String WorkComplete = txtAddTaskWorkComplete.getText();
        Date StartDate = startDateChooser.getDate();
        Date EndDate = endDateChooser.getDate();
        String StartTime = txtAddTaskStartTime.getText();
        String EndTime = txtAddTaskEndTime.getText();

        TimeUnit time = TimeUnit.MILLISECONDS;
        long StartTimeHour = time.convert(Long.parseLong(StartTime.split(":")[0]), TimeUnit.HOURS);
        long StartTimeMinute = time.convert(Long.parseLong(StartTime.split(":")[1]), TimeUnit.MINUTES);

        long EndTimeHour = time.convert(Long.parseLong(EndTime.split(":")[0]), TimeUnit.HOURS);
        long EndTimeMinute = time.convert(Long.parseLong(EndTime.split(":")[1]), TimeUnit.MINUTES);
        
        StartDate.setTime(StartDate.getTime() + StartTimeHour + StartTimeMinute);
        EndDate.setTime(EndDate.getTime() + EndTimeHour + EndTimeMinute);
        
        String StartDateText = dateFormat.format(StartDate);
        String EndDateText = dateFormat.format(EndDate); 

        String[] paramArray = {Name,Unit,WorkComplete,WorkTarget,StartDateText,EndDateText};
        System.out.println(paramArray[0]);
        db.runWriteQuery("insert into tasks (`task-name`, `task-unit`, `work-complete`, `work-target`, `create-date`, `deadline-date`)" +"values(?,?,?,?,?,?)",paramArray);
        
        this.dispose();
        MainFrame.setVisible(true);
    }//GEN-LAST:event_btnAddTaskSubmitActionPerformed

    private void btnAddTaskCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskCancelActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        MainFrame.setVisible(true);
    }//GEN-LAST:event_btnAddTaskCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
    /*    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTaskFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddTaskPanel;
    private javax.swing.JPanel addTaskEndPanel;
    private javax.swing.JPanel addTaskNamePanel;
    private javax.swing.JPanel addTaskStartPanel;
    private javax.swing.JPanel addTaskUnitPanel;
    private javax.swing.JPanel addTaskWorkCompletePanel;
    private javax.swing.JPanel addTaskWorkTargetPanel;
    private javax.swing.JButton btnAddTaskCancel;
    private javax.swing.JButton btnAddTaskSubmit;
    private com.toedter.calendar.JDateChooser endDateChooser;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser startDateChooser;
    private javax.swing.JTextField txtAddTaskEndTime;
    private javax.swing.JTextField txtAddTaskName;
    private javax.swing.JTextField txtAddTaskStartTime;
    private javax.swing.JTextField txtAddTaskUnit;
    private javax.swing.JTextField txtAddTaskWorkComplete;
    private javax.swing.JTextField txtAddTaskWorkTarget;
    // End of variables declaration//GEN-END:variables
}
