/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackage;

/**
 *
 * @author AK
 */
public class TaskCardPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaskCardPanel
     */
    public TaskCardPanel() {
        initComponents();
    }
    public class add{
        private void name(String str)
        {
            lblTaskNameAns.setText(str);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskCardPanel = new javax.swing.JPanel();
        workProgressBar = new javax.swing.JProgressBar();
        deadlineProgressBar = new javax.swing.JProgressBar();
        lblTaskName = new javax.swing.JLabel();
        lblRequire = new javax.swing.JLabel();
        addSpinner = new javax.swing.JSpinner();
        btnSpinnerSubmit = new javax.swing.JButton();
        lblWork = new javax.swing.JLabel();
        lblDeadline = new javax.swing.JLabel();
        lblTotalDeadline = new javax.swing.JLabel();
        lblTotalWork = new javax.swing.JLabel();
        lblTotalDeadlineAns = new javax.swing.JLabel();
        lblTotalWorkAns = new javax.swing.JLabel();
        lblTaskNameAns = new javax.swing.JLabel();

        taskCardPanel.setBackground(new java.awt.Color(255, 51, 204));

        lblTaskName.setText("Name of Task");
        lblTaskName.setMinimumSize(new java.awt.Dimension(0, 0));

        lblRequire.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequire.setText("minimum requirement : 1 task / day ");
        lblRequire.setMinimumSize(new java.awt.Dimension(0, 0));

        addSpinner.setMinimumSize(new java.awt.Dimension(4, 2));

        btnSpinnerSubmit.setText("Completed");
        btnSpinnerSubmit.setMinimumSize(new java.awt.Dimension(6, 2));

        lblWork.setText("Work");
        lblWork.setMinimumSize(new java.awt.Dimension(2, 1));

        lblDeadline.setText("Deadline");
        lblDeadline.setMinimumSize(new java.awt.Dimension(4, 1));

        lblTotalDeadline.setText("Deadline : ");
        lblTotalDeadline.setMinimumSize(new java.awt.Dimension(4, 1));

        lblTotalWork.setText("Total Work :");
        lblTotalWork.setMinimumSize(new java.awt.Dimension(3, 1));

        javax.swing.GroupLayout taskCardPanelLayout = new javax.swing.GroupLayout(taskCardPanel);
        taskCardPanel.setLayout(taskCardPanelLayout);
        taskCardPanelLayout.setHorizontalGroup(
            taskCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskCardPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(taskCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWork, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(taskCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taskCardPanelLayout.createSequentialGroup()
                        .addGroup(taskCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(taskCardPanelLayout.createSequentialGroup()
                                .addGap(431, 431, 431)
                                .addComponent(lblTotalWorkAns, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                            .addGroup(taskCardPanelLayout.createSequentialGroup()
                                .addGap(359, 359, 359)
                                .addComponent(lblTotalDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTotalDeadlineAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskCardPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(taskCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(taskCardPanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(addSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSpinnerSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))
                    .addGroup(taskCardPanelLayout.createSequentialGroup()
                        .addGroup(taskCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(workProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRequire, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(taskCardPanelLayout.createSequentialGroup()
                                .addComponent(lblTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTaskNameAns, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addComponent(deadlineProgressBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        taskCardPanelLayout.setVerticalGroup(
            taskCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taskCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalDeadlineAns))
                .addGap(5, 5, 5)
                .addGroup(taskCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taskCardPanelLayout.createSequentialGroup()
                        .addComponent(lblTotalWorkAns)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTaskNameAns, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTotalWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTaskName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(taskCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(taskCardPanelLayout.createSequentialGroup()
                        .addGroup(taskCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblWork, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(workProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(taskCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deadlineProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                            .addComponent(lblDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(taskCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSpinnerSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRequire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(taskCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner addSpinner;
    private javax.swing.JButton btnSpinnerSubmit;
    private javax.swing.JProgressBar deadlineProgressBar;
    private javax.swing.JLabel lblDeadline;
    private javax.swing.JLabel lblRequire;
    private javax.swing.JLabel lblTaskName;
    private javax.swing.JLabel lblTaskNameAns;
    private javax.swing.JLabel lblTotalDeadline;
    private javax.swing.JLabel lblTotalDeadlineAns;
    private javax.swing.JLabel lblTotalWork;
    private javax.swing.JLabel lblTotalWorkAns;
    private javax.swing.JLabel lblWork;
    private javax.swing.JPanel taskCardPanel;
    private javax.swing.JProgressBar workProgressBar;
    // End of variables declaration//GEN-END:variables
}
